### ISSUE TITLE
Import Different From Docs

### ISSUE THREAD

**Issue by ichasepucks** [grafana/xk6-exec#15]
I'm not sure if something changed recently but I could only get this imported using
```
import {command} from 'k6/x/exec';
```

The documentation suggests
```
import {exec} from 'k6/x/exec';
```

Then for usage I just use `command` instead of `exec.command`.  Unless I'm doing something unusual I suspect it's just a small documentation and sample update?

**Comment by mstoykov** [comment]
The documentation suggest

> import exec from 'k6/x/exec';

Which is a [default import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#default_import) where in reality the name does not matter. It could've been: 

> import something from 'k6/x/exec';

Your code

> import {exec} from 'k6/x/exec';

or 

> import {command} from 'k6/x/exec';

are [named imports](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#named_import) which import specifically `exec` or `command` identifiers from the module.

But this module *only* exports `command`, but its default export is combination of all it's named ones.  

I don't think this has changed for quite a while this looks a lot like something that you just mistyped.

I will close this, but if you think I am wrong or somewhere this is documented differently - please comment and I will reopne it.
